### ISSUE TITLE
[SubRip to WebbVTT] Multi-line presented as single line

### ISSUE THREAD

**Issue by chenlung** [delphiki/SubRip-File-Parser#7]
http://atelier.u-sub.net/srt2vtt/

**Expected result:**

1
00:00:00.122 --> 00:00:03.600
Testing the functionality of
the SubRip to WebVTT converter

**Actual result:**

1
00:00:00.122 --> 00:00:03.600
Testing the functionality ofthe SubRip to WebVTT converter

**Comment by chenlung** [comment]
My apologies if I have perhaps missed something.

Can you advise?

**Comment by delphiki** [comment]
Hi @chenlung.

As said in the README, this repo is out of date, and no longer maintained.
The converter is still based on this lib, so probably buggy.

I'll try to find find some time to port it on the new project: https://github.com/captioning/captioning

**Comment by chenlung** [comment]
Ah yes @delphiki, sorry - I didn't see it.

Thank you for your reply and efforts.
